### ISSUE TITLE
Missing button

### ISSUE THREAD

**Issue by kinwolfqc** [jmcameron/attachments#1]
The button 'add attachment" appear correctly in articles but does not appear when we edit events in the OSSolution Event Booking extension.  All other plugin buttons appear correctly in that extension.  I have attached a screenshot showing where the Add Attachment is missing
![capture](https://cloud.githubusercontent.com/assets/9009158/6955316/a17e6080-d8a9-11e4-80b7-861f43e822ab.JPG)

**Comment by jmcameron** [comment]
I assume that "OSSolution Event Booking" is another extension.  If so, an
"Attachment plugin" will need to be written for that extension that lets
the Attachments extension know how to interact with the extension.  This is
not a simple process---and I do not have time to do it for you.   If you
are a PHP programmer, you can look at similar plugins that I've written for
SimpleEvents and JEvents at:

    https://github.com/jmcameron/attachments_for_simplecalendar

    https://github.com/jmcameron/attachments_for_jevents  AND
    https://github.com/jmcameron/attachments_for_jevents_save

There is a manual for writing these Attachments plugins at:

    http://jmcameron.net/attachments/

So the short answer is Attachments does not currently support this
extension, sorry.

Good luck with your site!

-Jonathan

**Comment by kinwolfqc** [comment]
Ah, ok, I thought it would load any place the editor was.  I'll take a look at those other 2 plugins.  Thanks!
