### ISSUE TITLE
Blank page in save when you edit an attachment in article

### ISSUE THREAD

**Issue by ribo72** [jmcameron/attachments#12]
Hello, in attachents 3.2.5 when you have it an article and you try to edit it(update this file) and in the end you hit save, it change it but it gives blank page. Please check it. Thank you.

**Comment by sksksksk** [comment]
I can confirm this. The same for trying to delete an attachment. I think it tries to open an inline popup, but instead a new page is opened with the deletion dialog. After deleting it, a blank page is displayed and a JS error that it can't find the parent window.
 attachents 3.2.5
Joomla 3.7.2

**Comment by jmcameron** [comment]
I think this version will fix this issue.  Please test it and let me know!   You should be able to install this over any existing version of Attachments.  But backup first!

    http://jmcameron.net/attachments/downloads/attachments-3.2.6-Beta3.zip

Please let me know how it works for you by posting here.  If it works for you and a few other testers, I'll push out a new release.

-Jonathan

**Comment by ribo72** [comment]
Hello, i tested and i saw that when you edit with pop up there is no blank page, but when you edit again and is with no pop up and the url is like /index.php?option=com_attachments&task=attachment.edit&cid[]=585&from=editor&tmpl=component , then you see blank page after the change of a file or url

**Comment by ribo72** [comment]
The blank page comes with url /index.php?option=com_attachments&task=attachment.save

**Comment by jmcameron** [comment]
Thanks.  I'll take another look at it tonight.

-Jonathan

**Comment by ribo72** [comment]
Thank you very much, i will waiting for your news.

**Comment by jmcameron** [comment]
Please try this version:

   http://jmcameron.net/attachments/downloads/attachments-3.2.6-Beta4.zip

-Jonathan

**Comment by ribo72** [comment]
Hello, again it shows blank page in administrator/index.php?option=com_attachments&task=attachment.save

**Comment by ribo72** [comment]
After that if i go to the article, it is locked and i must check in. I said that if this can help. I also put error reporting maximum but this is still blank page. Note that error reporting works fine for every other error

**Comment by jmcameron** [comment]
Please describe in detail how you get the blank page the first time (with Beta4).  Thanks.

**Comment by ribo72** [comment]
I am going to article with attachments inside(for example pdf) the first "Update this file" is with pop up, so there when i hit "save" there is no blank page. I try again to the same or another attachement in the same article to hit  "Update this file" and there is not open in pop up but in the same window and at the end when i hit "save" there is blank page

**Comment by jmcameron** [comment]
ribo72:  This is the back end, right?  Do you see the same issue in the front end article editor?

**Comment by ribo72** [comment]
Yes this is in backend. Wait a moment to see and in frontend to tell you

**Comment by ribo72** [comment]
I test it and in frontend and with protostar template and when you hit "Update this file" there is no pop up page, only you see "Update Attachment File" in the same window, (the example url is index.php?option=com_attachments&task=update&id=585&from=editor&tmpl=component) and when you hit "Update" it gives blank page with url /index.php?option=com_attachments&task=save&tmpl=component&from=editor

**Comment by jmcameron** [comment]
ok.  That is helpful.  I'll try to work on it some more this weekend.

**Comment by ribo72** [comment]
ok thank you, i hope to helped you with this test. 
Thanks again.

**Comment by vladmz** [comment]
I have installed 3.2.6 Beta 4. My observations are that when you select Edit a modal dialog opens containing the 'Update Attachment' page. Selecting Save dismisses the dialog and saves the changes which is great as this fixes the blank page issue and the 'refreshAttachments is not a function' error. However, when you try and select the edit icon again you get the 'Update Attachment' page appearing as its own page rather than in a modal dialog which is a return to the original problem. The workaround is to refresh the page after saving an attachment. I look forward to a more complete resolution to this problem.

**Comment by parapente** [comment]
Joomla 3 reached eol on 17 August 2023 so v3.x of the attachments is no longer supported. If any of the problems mentioned in the bug report persist in the latest version of the attachment package feel free to reopen.
