### ISSUE TITLE
attachments extension download issues

### ISSUE THREAD

**Issue by openenergyprojects** [jmcameron/attachments#13]
Hello,
I tried to download this extension, but all pages under your domain have some issues:
- http://jmcameron.net/attachments/updates/3.2.5/attachments-3.2.5.zip
- http://jmcameron.net/attachments/downloads/attachments-3.2.5.zip
All are `Forbidden` or do not exist.

The other ones are obsoleted as far as we understand:
http://joomlacode.org/gf/project/attachments3/frs/ , right?

**Comment by jmcameron** [comment]
Sorry about this.  My web hosting service just switched me to a new server.   This is a temporary problem and should be sorted out in a day or two.  Please try again tomorrow!

-Jonathan

**Comment by jmcameron** [comment]
These issue have been resolved.
