### ISSUE TITLE
Can't add new attachment

### ISSUE THREAD

**Issue by themella** [jmcameron/attachments#14]
Me and many other user have a lot of problem with joomla 3.7 update and your addon.
When you try do select 1 article for attachment we have this error in console :

Uncaught TypeError: Cannot read property 'xtd-articles' of null
    at Object.e.getOptions (core.js?415ece9…:1)
    at window.jSelectArticle (admin-articles-modal.min.js?415ece9…:1)
    at HTMLAnchorElement.<anonymous> (admin-articles-modal.min.js?415ece9…:1)

i think problem is new way for joomla to select article object

for us is really difficult to fix this issue can you try to fix it?

**Comment by jmcameron** [comment]
I'm aware of the problem and I'm trying to fix it.  Unfortunately, my time is very full right now and I haven't had the time to track down this problem.  Please be patient!

-Jonathan

**Comment by jmcameron** [comment]
I think this version will fix this issue.  Please test it and let me know!   You should be able to install this over any existing version of Attachments.  But backup first!

    http://jmcameron.net/attachments/downloads/attachments-3.2.6-Beta3.zip

Please let me know how it works for you by posting here.  If it works for you and a few other testers, I'll push out a new release.

-Jonathan

**Comment by jmcameron** [comment]
Fixed another issue.  Please try this version:

   http://jmcameron.net/attachments/downloads/attachments-3.2.6-Beta4.zip

-Jonathan
