### ISSUE TITLE
Problem with encoding in filenames

### ISSUE THREAD

**Issue by gregkoron** [jmcameron/attachments#18]
Hi, I would like to ask if anyone has reported problems with filenames that contain different to English characters. In my case the problem is spotted when in K2 items I upload (attach) files with names that contain Greek characters. Then, once the K2 item is saved the filename is converted to something else. Does anyone know how to fix this?

Thank you in advance for any assistance!

**Comment by parapente** [comment]
@gregkoron closing as there doesn't seem to be a problem with file encoding in recent versions of the extension. Feel free to reopen if the problem persists. I use mostly Greek characters for filenames and I haven't noticed any problems so far.
