### ISSUE TITLE
SQL Injection ?

### ISSUE THREAD

**Issue by jcbravo** [jmcameron/attachments#19]
Where ? how can we fix it?

https://vel.joomla.org/vel-blog/2127-attachments-3-2-5-sql-injection

**Comment by jmcameron** [comment]
Thank you.  I heard about this but have not had a chance to fix it yet.

-Jonathan

**Comment by Klipper** [comment]
When you expect to have this fixed? Because we use attachments very much on our site.

**Comment by jmcameron** [comment]
I hope to fix it this weekend.

-Jonathan

**Comment by jcbravo** [comment]
Hello @jmcameron , Is the SQL injection fixed in 3.2.6 ?

**Comment by jmcameron** [comment]
I have fixed this but it is going to take a day or two to release it.  In the meantime, here is the link to a fixed version:

   http://jmcameron.net/attachments/downloads/attachments-3.2.6-Beta5.zip

As usual, you should be able to install this over any existing version.   Backup first!

This version has a couple of small issues that I will address in a follow-up release.

-Jonathan

**Comment by jcbravo** [comment]
Thank you @jmcameron
