### ISSUE TITLE
Upgrading from 3.1.3 to 3.2.3 fails

### ISSUE THREAD

**Issue by daviddwuci** [jmcameron/attachments#2]
Using the Joomla extension manager in Joomla 3.4.1, upgrading Attachments from 3.1.3 to 3.2.3 fails with the following message:
>Error
>
>Error moving the 'attachments' directory out of the way to install the Attachments extension. Temporarily rename/move the 'attachments' directory and retry the installation.
>
>Error installing package

Attempting to install using the packaged zip results in the same error. What is the correct upgrade procedure? I could not find any proper documentation.

**Comment by jmcameron** [comment]
Please read the suggestion in the error message!

Temporarily rename the 'attachments' directory to something else (using
FTP, for instance).  Then install Attachments and then rename the
attachments directory back to 'attachments'.

Try that and let me know if that fails.

The reason there is no 'proper' documentation is that this usually works
(many thousands of installations).  I'm not sure why it is having
difficulties in your installation.

-Jonathan

**Comment by jmcameron** [comment]
I would like to track this problem down.  Could you provide some info for me:
  * What OS is on your server?
  * Do you have any extensions or server settings that control file access?
Thanks
-Jonathan

**Comment by daviddwuci** [comment]
Hi Jonathan, moving it out of the way then back seems to have worked. I didn't know if this was safe for the upgrade, and didn't want to lose or corrupt any data.

I am running Ubuntu 14.04.2 with Apache 2. I don't have anything special that controls file access per say, but the root www directory is owned by root and thus www-data does not have write access to it.

Thank you for your help!

**Comment by jmcameron** [comment]
That is probably the problem.  Joomla (hence Apache+PHP) tries to move the
'attachments' directory aside during installation.  It may not have
adequate privileges.

Just be aware of the issue.  You may want to see if you can get the Joomla
site directory group ownership set to www-data (whatever group Apache runs
the web server with) so you do not have this problem in the future.

Glad you got it working.

-JOnathan
