### ISSUE TITLE
att. with modern router not shows in article

### ISSUE THREAD

**Issue by phudak** [jmcameron/attachments#20]
Joomla 3.8.x with modern router turned ON  and option "remove ID from url" article attachements not appears in article view.

https://docs.joomla.org/J3.x:New_Routing_System

**Comment by stefano-buscaglia** [comment]
hi,
I confirm that isseue. 

In my case the arrachments files are showed in the article view only if  I disable off the  the SEO url or I use the  "legacy" Routing.

With the SEO active, and the modern router active with the option "remove ID from url" I can see  attachments files in the blog view as aspected.

S.

**Comment by yozmag** [comment]
I think it's  not working when layout is 'blog' and view is 'article', config (Hide attachments on blog pages) is going to hide when you enter an article from a category blog.
Changing attachments_for_content.php near line 150 helps. Can you both test this?
		if (version_compare(JVERSION, '3.4.0', 'ge') AND
			//($view == 'category') AND ($layout == 'blog') AND ($parent_entity == 'article'))
			($view == 'article') AND ($layout == 'blog') )
		{
			$text_field_name = 'text';
		}

**Comment by dontroedel** [comment]
Hey,
I have the same problem.

When I open an normal article, everything works fine. When an article belongs to a category and this is opened via category blog, no attachments are shown. When I turn off modern routing, everything works fine again.

@yozmag: I tested it and it doesn´t work here.

Greetings

**Comment by yozmag** [comment]
I'm sorry to here that. I'm using joomla 3.9.2, in the article option integration tab I have URL routing "modern" and remove ids from url "no"  I if try with "yes" and it works too.
The file I have changed is in plugins/attachments/attachments_for_content can you check that again.
Thanks.

**Comment by felixkat** [comment]
> 
> 
> I'm sorry to here that. I'm using joomla 3.9.2, in the article option integration tab I have URL routing "modern" and remove ids from url "no" I if try with "yes" and it works too.
> The file I have changed is in plugins/attachments/attachments_for_content can you check that again.
> Thanks.

Joomla! 3.9.6, modern router, category blog.  The above changed works.

**Comment by parapente** [comment]
The issue seems to be fixed in the latest version of the extension (v4.0.2). Closing as fixed.
