### ISSUE TITLE
Are you still managing the attachments extension?

### ISSUE THREAD

**Issue by Klipper** [jmcameron/attachments#24]
Are you still managing the attachments extension?

I ask because alle links to your site: http://jmcameron.net/attachments/* are not working anymore. Also all links on the Joomla Extensions Directory (JED) to your extension are dead.

Regards,
Klipper

**Comment by jmcameron** [comment]
Yes, still maintaining it at a low level (when I can break away from other things).   

Fixed the website.  Please try it again.  The links in the JED should work  again.

-Jonathan

**Comment by Klipper** [comment]
Hi Jonathan,

Thanks for fixing. The live-update link (http://jmcameron.net/attachments/updates/updates.xml) is working again. And the links on the JED ar alive again.
Regards,
Klipper
