### ISSUE TITLE
Filename filters no error message on frontend

### ISSUE THREAD

**Issue by NioBee** [jmcameron/attachments#25]
Hello,

I have set up some filters in the configuration in order to avoid that my authors upload files with strange characters or too long filenames on my site (it happened on my previous site causing a lot of trouble).. when I work backend all works like a charm, if I try to upload a file that does not match my criteria the name gets trimmed if too long 
![name too long backend](https://user-images.githubusercontent.com/41695549/54031747-e6df8000-41af-11e9-9ff2-21deba93f985.PNG)
, or I get a message if a character in the filename isn't allowed.. 
![error on backend](https://user-images.githubusercontent.com/41695549/54031753-ec3cca80-41af-11e9-9497-46cd2768dfec.PNG)

On frontend, if a filename is too long it gets trimmed correctly but the user receives no alert message.
![frontend](https://user-images.githubusercontent.com/41695549/54031762-f363d880-41af-11e9-9a5a-748b4c42bd09.PNG)

When trying to attach a file with unallowed characters in the name, I don't get any type of error message.. the pop up window just stays white and nothing happens..
![frontend same file](https://user-images.githubusercontent.com/41695549/54031765-f8288c80-41af-11e9-83cb-2a93edb897b5.PNG)

is this a bug?

**Comment by yozmag** [comment]
Can you try this Pull request, and see if you find the same issue. #23 .

**Comment by NioBee** [comment]
I'm quite a newbie.. how can I try that method?

**Comment by parapente** [comment]
This issue seems to be fixed in the latest version of the extension (v4.0.2). Closing as fixed.
