### ISSUE TITLE
Blank modal when trying to delete an attachment

### ISSUE THREAD

**Issue by GuyonWoW** [jmcameron/attachments#26]
Joomla 3.8.8
Attachments Version 3.2.6
PHP Versione and server details: http://webs3.apkappa.it/pi.php

Whenever i try to delete an attachment from the frontend side i see a blank modal window.
Editing an attachment works.
All the operations from the backend works.

![Screenshot](https://user-images.githubusercontent.com/4330093/58088952-0d646300-7bc4-11e9-9f94-005c06b63a0f.png)

I tried to reinstall it, i tried different joomla versions, nothing seem to fix it.

Any idea?
Thank you.

**Comment by parapente** [comment]
Joomla 3 reached eol on 17 August 2023 so v3.x of the attachments is no longer supported. If any of the problems mentioned in the bug report persist in the latest version of the attachment package feel free to reopen.
