### ISSUE TITLE
Quite frequently attaching a new file make it appearing twice both in frontend and backend

### ISSUE THREAD

**Issue by fm83** [jmcameron/attachments#28]
Hi

For several months now, when managers of my website attach a new file using your component, this file appear twice in both backend and frontend.
Did you eared about that issue already? Any idea of where it could come from?

Than you

**Comment by parapente** [comment]
Joomla 3 reached eol on 17 August 2023 so v3.x of the attachments is no longer supported. If any of the problems mentioned in the bug report persist in the latest version of the attachment package feel free to reopen.
