### ISSUE TITLE
php8 Error in Backend -> Option

### ISSUE THREAD

**Issue by st-anton** [jmcameron/attachments#29]
Hi, when stepping over to php8, the backend options page cannot be opened because of a error:  `count(): Argument #1 ($var) must be of type Countable|array, null given `
Frontend does work and adding new attachments does work as well.

**Comment by peterhulst** [comment]
You can correct that easily.
File: /administrator/components/com_attachments/controllers/params.php
Line:
		if (count($errors = $this->get('Errors'))) {
replace that line with:
		$errors = $this->get('Errors');
		if (!IS_NULL($count) and count($errors)) {

**Comment by Kimball31** [comment]
@peterhulst, don't you mean !IS_NULL($errors),  not !IS_NULL($count)?
```
        $errors = $this->get('Errors');
        if (!IS_NULL($errors) and count($errors)) {
            JError::raiseError(500, implode("\n", $errors) . ' (ERR 118)');
            return false;
        }
```

**Comment by peterhulst** [comment]
You are right. I have corrected it.

**Comment by mckillo** [comment]
This issue is fixed and it could be closed.
