### ISSUE TITLE
php8 Warnings in Frontend

### ISSUE THREAD

**Issue by st-anton** [jmcameron/attachments#30]
On some pages (I don't know the reason), there are warnings in the page on top of the content:
`Warning: Undefined array key 0 in \plugins\attachments\attachments_for_content\attachments_for_content.php on line 827

Warning: Attempt to read property "created_by" on null in \plugins\attachments\attachments_for_content\attachments_for_content.php on line 827

Warning: Undefined array key 0 in \plugins\attachments\attachments_for_content\attachments_for_content.php on line 828

Warning: Attempt to read property "catid" on null in \plugins\attachments\attachments_for_content\attachments_for_content.php on line 828`

**Comment by Kimball31** [comment]
Here's what I did to fix that PHP warning:

Change \plugins\attachments\attachments_for_content\attachments_for_content.php on lines 826-828:
`
			// See if the options apply to this article
			$created_by = (int) $attachments[0]->created_by;
			$catid	    = (int) $attachments[0]->catid;
`

This this:

`	    
            // See if the options apply to this article 
            // (Revised for PHP7)
            if(is_object($attachments))
            {
			    $created_by = (int) $attachments[0]->created_by;
			    $catid		= (int) $attachments[0]->catid;
            }
            else
            {
                             $created_by = false;
                             $catid      = false;
            }`

**Comment by JLTRY** [comment]
please use last version available for Joomla 4.x Joomla 5.x

**Comment by tiropictor** [comment]
I've got very similar warnings (except for line numbers) on Joomla 5.1.1, php 8.2.20, using latest component version 4.0.1:


Warning: Undefined array key 0 in /var/www/html/plugins/attachments/attachments_for_content/attachments_for_content.php on line 842

Warning: Attempt to read property "created_by" on null in /var/www/html/plugins/attachments/attachments_for_content/attachments_for_content.php on line 842

Warning: Undefined array key 0 in /var/www/html/plugins/attachments/attachments_for_content/attachments_for_content.php on line 843

Warning: Attempt to read property "catid" on null in /var/www/html/plugins/attachments/attachments_for_content/attachments_for_content.php on line 843


It appeared on top of "Category List" type menu item. So **_workaround_** for me was in Components > Attachments > Options, Visibility tab, and there `turn on` "Hide attachments except on article views" and `turn off` "Always show attachments on category views".

Then warnings went away. But problem is still somewhere there, we all know 😉

**Comment by parapente** [comment]
@tiropictor can you please test the pull request? It should make the warnings disappear.

**Comment by tiropictor** [comment]
@parapente nope. unfortunately it doesn't:

Warning: Undefined array key 0 in /var/www/html/plugins/attachments/attachments_for_content/attachments_for_content.php on line 844

Warning: Attempt to read property "catid" on null in /var/www/html/plugins/attachments/attachments_for_content/attachments_for_content.php on line 844

![image](https://github.com/jmcameron/attachments/assets/61196357/73c03be8-84e4-49ac-8cd2-d7347c84a6ba)

**Comment by parapente** [comment]
@tiropictor you are right. I managed to reproduce the error and modified the check accordingly in the PR.

**Comment by tiropictor** [comment]
@parapente perfecto, warning are gone!
