### ISSUE TITLE
Attachments for Joomla 4?

### ISSUE THREAD

**Issue by bsylwek** [jmcameron/attachments#31]
Hallo
Attachments is a very good and functional component.. Will there be Attachments for Joomla 4? Do you have to program the entire component from scratch or is it enough to just correct a fragment of the code to run on Joomla 4?

Thank you!

**Comment by jmcameron** [comment]
Regretfully, I am not able to maintain the Attachments plugin for Joomla now; I simply do not have time.

I do not know how much work will be necessary to adapt it to Jooma 4.

-Jonathan

**Comment by bsylwek** [comment]
I don't know what to do, I have had a lot of attachments for many years. The component works stably for me even on joomla 3.10.1 There is practically no competition.

**Comment by yozmag** [comment]
> 
> 
> I don't know what to do, I have had a lot of attachments for many years. The component works stably for me even on joomla 3.10.1 There is practically no competition.

I have used it on Joomla! 3.9.28 Stable on test instalation and it is ok. Joomla 4 is just out now why your rust to go to joomla 4.
I can see what the issues are on joomla 4 and fix it, but no promises.

**Comment by SonkinS** [comment]
> Regretfully, I am not able to maintain the Attachments plugin for Joomla now; I simply do not have time.
> 
> I do not know how much work will be necessary to adapt it to Jooma 4.

Is there a version for Joomla 4 planned sometime in the future?

**Comment by m04a** [comment]
I also will try to adapt it.. I also don't promise anything

**Comment by qg11** [comment]
I've also used Attachments for many years and am interested in some way to migrate it.  Thanks for any help you can provide, and I understand no promises can be made.  Best regards.

**Comment by pepperstreet** [comment]
Following…

**Comment by yozmag** [comment]
I'm working on this, no date for the release for now.

**Comment by m04a** [comment]
It wasn't a top priority for my client at the end so we just deleted than feature. I hope someone can help you

**Comment by quuki** [comment]
Hey. I'm desperate! I have been using attachments on several of my sites for years. I haven't found anything similar or better. And there is no such thing! I love attachments and I really hope that there will be a solution to support for J4. I could even buy attachments extension!

regards /q

**Comment by parapente** [comment]
Please test the latest release and report any bugs you might find. Beware that version 4.0 of attachments is not compatible with Joomla 3.x so it should be installed after upgrading your site to Joomla 4.
