### ISSUE TITLE
Support Joomla 4 "Attachments"

### ISSUE THREAD

**Issue by mediaDESIGN-SK** [jmcameron/attachments#32]
Hi Jonathan,
You have programmed the Joomla extension "Attachments". In the projects I oversee for my clients as a web designer, I have often used this extension. Joomla 4 has been stable for productive use for some time now. I am in the process of migrating my client project to Joomla 4. Unfortunately, I have to state that "Attachments" is not yet available for Joomla 4 and I assume because the jmcameron.net site is not providing any content that you are no longer active. Can you please enlighten me whether there will be a J!4 version for "Attachments".
If not, I could offer you to take over this component from you, including all rights to it. I would then make them ready for Joomla4. If this is conceivable for you, I would ask you for feedback and your ideas on the transfer of rights.

**Comment by yozmag** [comment]
Hello, I have contacted Jonathan about this same issue, I told me he didn't had time at the moment to make the changes for the joomla 4. But if I made the changes and make a pull request he would accept it.
I have start to make changes but I'm half way. Maybe we can join efforts.

**Comment by mediaDESIGN-SK** [comment]
We can team up, but I would actually only want to make the effort if I could take over the project with the copyright and then be allowed to market it on . I estimate the effort at about 4-5 days. Would be good to know if Jonathan would agree.

**Comment by yozmag** [comment]
I'm trying to remove all dependency of attachment plugin manager, there is lot of code with joomla 1.5 and 2.5 checks.
I'm looking at weblinks joomla component and implement the same way in the attachment component.
There has to be a new smart search plugin for attachments.
Hope you can make it in 4-5 days. You can contact me joao.verissimo [ *@*] cm-ferreiradozezere.pt . thank you.

**Comment by SonkinS** [comment]
> We can team up, but I would actually only want to make the effort if I could take over the project with the copyright and then be allowed to market it on . I estimate the effort at about 4-5 days. Would be good to know if Jonathan would agree.

There are thousands of sites that use Attachments under the GNU/GPL license.
We will all be very sad if the component becomes paid!

**Comment by jmcameron** [comment]
I disagree with Attachments becoming a paid plugin.
I still do not have time to work on it, sorry.

-Jonathan

**Comment by mediaDESIGN-SK** [comment]
Yes, what good is it if there isn't a new version that is Php8 compatible and doesn't go with Jooml4. I accept and respect Jonathan's decision. But my motivation is not high enough to put energy into it. There are only a few customer projects that use it. These customers are not willing to pay for it for 4-5 days. Also, there are alternatives.
Maybe Jonathan wants to develop it himself. I'm glad we found him here and he's speaking up. Maybe he realizes that the community loves his extension. With a small donation I would support the development if it works with Php8 and J4.

**Comment by reilldesign** [comment]
@mediaDESIGN-SK, there is an initial commit to prepare Attachments plugin to work with Joomla 4.
[https://github.com/yild/attachments](url)

**Comment by parapente** [comment]
Please test the latest release and report any bugs you might find. Beware that version 4.0 of attachments is not compatible with Joomla 3.x so it should be installed after upgrading your site to Joomla 4.

**Comment by mediaDESIGN-SK** [comment]
I tested this new version. It works in Joomla 4 but not in Joomla 5. It works in Joomla Blog Pages but it doesn't seem to work in Joomla Article Pages with Joomla 4.

**Comment by parapente** [comment]
@mediaDESIGN-SK please open a new bug report with details about what exactly doesn't work in Joomla 4. Are you trying to create a new article and the button to add attachment doesn't work? Are you using the frontend or the backend to create the article? Does it work correctly when creating the article and the attachment doesn't appear on the site? Is the attachment appearing in the article and you cannot download the file? Please be more specific so we can narrow down the cause.
