### ISSUE TITLE
Bug new release for joomla 4

### ISSUE THREAD

**Issue by ArnyLt** [jmcameron/attachments#38]
Doesn t work :

![image](https://github.com/jmcameron/attachments/assets/124058778/83a0a22f-93b4-488c-9bc3-61a193b29496)

**Comment by JLTRY** [comment]
Hello my questions:

- what is your version of joomla ?
- did you do a 1st install or an upgrade?
- if upgrade which version of joomla did you have before, and did you uninstall the component ?
 
-could you please set debug mode as true in the joomla configuration and capture the error with the full stack

**Comment by JLTRY** [comment]
It seems you loose your parameters . The line is $params = ComponentHelper::getParams('com_attachments');
You should reinstall com_attachments or check your databse
Normally you should have an entry in table joomxx_extensions
com_attachments
with value params = {"publish_default":"1","auto_publish_warning":"","default_access_level":"3","user_field_1_name":"","user_field_2_name":"","user_field_3_name":"","max_filename_length":0,"attachments_placement":"custom","allow_frontend_access_editing":"0","show_column_titles":"0","show_description":"1","show_creator_name":"0","show_file_size":"1","show_downloads":"0","show_created_date":"0","show_modified_date":"0","date_format":"Y-m-d H:i","sort_order":"filename","hide_on_frontpage":"0","hide_with_readmore":"0","hide_on_blogs":"0","hide_except_article_views":"0","always_show_category_attachments":"1","show_guest_access_levels":["1"],"hide_add_attachments_link":"0","max_attachment_size":0,"forbidden_filename_characters":"#=?%&","attachments_table_style":"attachmentsList","file_link_open_mode":"in_same_window","attachments_titles":"","link_check_timeout":"10","superimpose_url_link_icons":"1","suppress_obsolete_attachments":"0","login_url":"index.php?option=com_users&view=login","register_url":"index.php?option=com_users&view=registration","secure":"0","download_mode":"inline"}

**Comment by ArnyLt** [comment]
With a restauration of parameters, it works.

Thanks a lot for your help.
