### ISSUE TITLE
No scroll bar with files on popup to add a file 

### ISSUE THREAD

**Issue by fredlang7680** [jmcameron/attachments#42]
Hello, 

We have an issue on the popup to add a file, we can not view all the files in the popup. It's not serious, but we have a solution for you:

![image](https://github.com/jmcameron/attachments/assets/56043103/bb3ac58a-5358-4a55-932c-35ac260473dd)

You just have to put yes to scroll bar in iframe config :
![image](https://github.com/jmcameron/attachments/assets/56043103/21f74f49-89f4-45b0-a468-951f9a9de8d3)

Regards,

**Comment by parapente** [comment]
Thank you for the report. I will have a look at it to make the modal be responsive and add a scrollbar.
