### ISSUE TITLE
Add an attachmentURL is not possible on Joomla 4.x or Joomla 5.x

### ISSUE THREAD

**Issue by JLTRY** [jmcameron/attachments#50]
In the backend I try t add an attachment based on an URL
When I click on Upload I have got an issue
ATTACH_ERROR_SAVING_URL_ATTACHMENT_RECORD Incorrect integer value: '' for column 'url_valid' at row 1 (ERR 40) 
_To be noticed that it works on my joomla 3.x site with old component version_

**Comment by parapente** [comment]
To keep track of the issue, I also get "ATTACH_ERROR_SAVING_URL_ATTACHMENT_RECORDField 'filename_sys' doesn't have a default value (ERR 40)" in a joomla 5 test site I have.

**Comment by JLTRY** [comment]
Yes for me too. The error is present on both joomla 4 and 5
 I have kept my old sites for joomla 3 and 4
It works only on joomla 3.x
