### ISSUE TITLE
error when downloading attachment

### ISSUE THREAD

**Issue by etsc-webmaster** [jmcameron/attachments#55]
0 Call to undefined method JMCameron\Component\Attachments\Administrator\Model\AttachmentModel::setId():

No | Function | Location
-- | -- | --
1 | () | JROOT/components/com_attachments/src/Helper/AttachmentsHelper.php:1512
2 | JMCameron\Component\Attachments\Site\Helper\AttachmentsHelper::download_attachment() | JROOT/administrator/components/com_attachments/src/Controller/AttachmentController.php:1120
3 | JMCameron\Component\Attachments\Administrator\Controller\AttachmentController->download() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
4 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
5 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
6 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
7 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
8 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
9 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
10 | require_once() | JROOT/administrator/index.php:32

**Comment by parapente** [comment]
Please specify the Joomla version, Attachment extension version and the browser you are using.

**Comment by etsc-webmaster** [comment]
hi 
thanks
it is ‎4.4.4

**Comment by etsc-webmaster** [comment]
I have found the error
JROOT/components/com_attachments/src/Helper/AttachmentsHelper.php:1510

change
	$model = $mvc->createModel('Attachment');
	
	to 
	
		$model = $mvc->createModel('Attachment','Site');
		
		this would point the code to the correct modle file in the site dir not admin
		thanks

**Comment by parapente** [comment]
I cannot recreate the error with the latest version of attachments extension. Can you please try version 4.0.1 if you don't have it installed?

**Comment by JLTRY** [comment]
@etsc-webmaster I did not reproduce the issue with latest version of attachment https://github.com/jmcameron/attachments/releases/download/v4.0.1/attachments-4.0.1.zip and joomla 4.4.4

**Comment by JLTRY** [comment]
@etsc-webmaster I propose to close the issue

**Comment by JLTRY** [comment]
Not reproduced
