### ISSUE TITLE
Problem with file downloading

### ISSUE THREAD

**Issue by mamabethe2** [jmcameron/attachments#6]
Hi Jonathan!

I have a problem with your joomla extension attachments 3.2.3
i can upload the files normally, but if i try to download the files, it looks, as the files are broken.

i can't find any system behind, but with some files it work fine.
Often the problem occurs with *.pdf's but also with *.odt (open office files)

If i try to open the *.odt file, i get following message:

---

Warning: set_time_limit() has been disabled for security reasons in /home/u853176370/public_html/components/com_attachments/helper.php on line 1590
PKŜSG^?

---

With pdf's i only get the message, that i can't open the file. 

I'm working with kubuntu and firefox, is that the problem?

Can you help me? Which additional information do you need? Do you have any idea?

Thank you in advance

Markus

**Comment by jmcameron** [comment]
Hi Markus,

Please try this (unreleased) version first and let me know if it helps.

   http://jmcameron.net/attachments/downloads/attachments-3.2.4-Beta5.zip

What is the mime type for the problematic attachments (edit the attachment
in the back end to see).

Also, there is an Attachments option on whether the attachment should be
downloaded inline or as a normal download.  You might want to experiment
with that setting to see if makes any difference.

I'm aware of some issues related to what you're talking about but they have
to do with problematic browser settings, not the Attachments extension
itself.  You may be able to do some searches to find out more.

-Jonathan

**Comment by mamabethe2** [comment]
Dear Jonathan!

Thanks for your prompt replay- now i had time to try your tips -
unfortunately your beta version didn't help, so we had to found an other
solution. Now we work with "SP Download"

Best regards.

2015-10-20 21:00 GMT+02:00 Jonathan Cameron <notifications@github.com>:

> Hi Markus,
>
> Please try this (unreleased) version first and let me know if it helps.
>
> http://jmcameron.net/attachments/downloads/attachments-3.2.4-Beta5.zip
>
> What is the mime type for the problematic attachments (edit the attachment
> in the back end to see).
>
> Also, there is an Attachments option on whether the attachment should be
> downloaded inline or as a normal download. You might want to experiment
> with that setting to see if makes any difference.
>
> I'm aware of some issues related to what you're talking about but they have
> to do with problematic browser settings, not the Attachments extension
> itself. You may be able to do some searches to find out more.
>
> -Jonathan
>
> On Tue, Oct 20, 2015 at 11:53 AM, mamabethe2 <notifications@github.com>
> wrote:
>
> > Hi Jonathan!
> >
> > I have a problem with your joomla extension attachments 3.2.3
> > i can upload the files normally, but if i try to download the files, it
> > looks, as the files are broken.
> >
> > i can't find any system behind, but with some files it work fine.
> > Often the problem occurs with *.pdf's but also with *.odt (open office
> > files)
> >
> > Can you help me? Which additional information do you need? Do you have
> any
> > idea?
> >
> > Thank you in advance
> >
> > Markus
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jmcameron/attachments/issues/6>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jmcameron/attachments/issues/6#issuecomment-149667936>
> .
>



-- 
Mit freundlichen Grüßen


das Team von Mama Bethe

**Comment by jmcameron** [comment]
Good luck with your site.  Glad to hear "SP Download" helped with your
problem.

-Jonathan
