### ISSUE TITLE
Unable to run joomla.php finder:index -vvv

### ISSUE THREAD

**Issue by yozmag** [jmcameron/attachments#61]
I'm trying to run php joomla.php finder:index -vvv and TypeError is lunched at  Joomla\CMS\Plugin\CMSPlugin->__construct() at /plugins/content/attachments/attachments.php:71

I think that finder for content calls out all plugins for content, but since this is running from the terminal it "Cannot assign Joomla\CMS\Application\ConsoleApplication to property PlgContentAttachments::$app".

**Comment by parapente** [comment]
@yozmag can you please try the fix fro the pull request? It should fix the problem you mention.
