### ISSUE TITLE
Fix "Error uploading file - Illegal file extension"

### ISSUE THREAD

**Issue by mckillo** [jmcameron/attachments#63]
![image](https://github.com/user-attachments/assets/e6b8b4c0-8275-480c-b502-a509a07c8183)

Error when attaching a file to an article in Joomla 5.1.2 (migrated from J3.10 -> J4.4 -> J5.0) with Attachments v.4.0.2 installed.

I debugged the issue and identified both the origin and the solution.

This Joomla installation was migrated from a previous version, and when I checked the media settings, I found this:

![image](https://github.com/user-attachments/assets/fe6e0a6e-1a6e-4d91-9229-15c5715b2ec9)

However, in the database, this setting is missing, and com_media has the following content in the params field:

`{"upload_extensions":"bmp,csv,doc,gif,ico,jpg,jpeg,odg,odp,ods,odt,pdf,png,ppt,swf,txt,xcf,xls,BMP,CSV,DOC,GIF,ICO,JPG,JPEG,ODG,ODP,ODS,ODT,PDF,PNG,PPT,SWF,TXT,XCF,XLS,mp3,webp,pdf","upload_maxsize":"25","file_path":"images","image_path":"images","restrict_uploads":"1","check_mime":"1","image_extensions":"bmp,gif,jpg,png,webp","ignore_extensions":"","upload_mime":"image\/jpeg,image\/gif,image\/png,image\/bmp,application\/x-shockwave-flash,application\/msword,application\/excel,application\/pdf,application\/powerpoint,text\/plain,application\/x-zip","upload_mime_illegal":"text\/html"}`

This is the Joomla 3.x setting, but Joomla 5 is displaying the default fields, and this setting isn't saved in the database. When the Attachments extension checks it in \components\com_attachments\src\Helper\AttachmentsHelper.php on line 629:

![image](https://github.com/user-attachments/assets/7546474f-5107-4864-95ba-1920d73f0448)

The 'if' statement on line 629 fails because the PDF extension isn't in the array.

**Solution:**
1. Open 'Media Settings' from the Joomla menu (Content - Media - Options) and click the 'Save & Close' button. This will save the default settings of the 'Media' component in Joomla 5, and the params field of com_media in the database will now contain the correct content:

`{"upload_maxsize":"25","file_path":"images","image_path":"images","restrict_uploads":"1","restrict_uploads_extensions":"bmp,gif,jpg,jpeg,png,webp,avif,ico,mp3,mp4,odg,odp,ods,odt,pdf,ppt,txt,xcf,xls,csv","check_mime":"1","image_extensions":"bmp,gif,jpg,png,webp","audio_extensions":"mp3,m4a,mp4a,ogg","video_extensions":"mp4,mp4v,mpeg,mov,webm","doc_extensions":"doc,odg,odp,ods,odt,pdf,ppt,txt,xcf,xls,csv","ignore_extensions":"","upload_mime":"image\/jpeg,image\/gif,image\/png,image\/bmp,application\/x-shockwave-flash,application\/msword,application\/excel,application\/pdf,application\/powerpoint,text\/plain,application\/x-zip"}`

Now, the error was solved (he code find the restrict_uploads_extensions key) and I can upload my attachment file into the article using the Attachments extension. I hope this helps other users facing the same issue.

**Comment by parapente** [comment]
I also stumbled upon this problem but the problem exists in com_media and not the attachments component/plugins. Joomla changed the way parameters are saved in the database and unfortunately the old settings are not saved in the new format when upgrading joomla. You just have to save the new settings one time and the problem disappears.

**Comment by mckillo** [comment]
I agree, this is a Joomla issue, but the error appears in the upload view of the Attachment. The user doesn't realize it's a Joomla issue and might think it's a problem with the extension. I discovered the source through debugging, but I believe it was a Joomla error since the extension list in the `com_media` settings appears correct.

**Comment by parapente** [comment]
The only thing that we can do is check if the the list is empty and display an extra warning for the user. I'll have a look at it in the weekend.

**Comment by mckillo** [comment]
It could be a good solution for the user to include a prompt to save the media settings. This way, the user/admin won't need to search online for a possible solution. Thanks.

**Comment by parapente** [comment]
@mckillo I just added PR #66 for this issue.
