### ISSUE TITLE
Invalid JSON inserted into _extensions

### ISSUE THREAD

**Issue by lars-star** [jmcameron/attachments#68]
On installing 4.0.2 into Joomla the Attachments management pages all returned a JSON error. All site pages returned the same error unless I disabled most of the Attachment plugins.

I found the com_attachments entry in the _extensions table contained escape characters in the params field, i.e. {\"secure\":\"1\"}. Correcting this allowed the extension to work.

Thanks for updating this extension, I've not found anything to better it.

**Comment by JLTRY** [comment]
Hello nobody reproduced this issue.
Do you have the file and the modification?
Can you propose a pull request ?

**Comment by lars-star** [comment]
On reflection it may be an issue with my installation of Joomla. I installed your package into another Joomla instance with no installation issue.
