### ISSUE TITLE
7z extention problem

### ISSUE THREAD

**Issue by xprspro** [jmcameron/attachments#72]
Joomla 5.1.0
I could not upload attachments with 7Z Extension and got the error message, "The most recent request was denied because it had an invalid security token. Please refresh the page and try again."

**Comment by parapente** [comment]
Have you added the 7z extension in Content -> Media -> Options ?

**Comment by xprspro** [comment]
yes off course, but i think the problem is with the file size limit not with the extensions, even a file not over the size limit it have the problem!
![123](https://github.com/user-attachments/assets/453d1984-16b7-4732-8826-7bcbe7689c39)

**Comment by JLTRY** [comment]
@xprspro do you have access to your Apache configuration ?
See also
https://stackoverflow.com/questions/43184232/the-most-recent-request-was-denied-because-it-contained-an-invalid-security-toke

**Comment by xprspro** [comment]
Hi
I performed tests. One of them is restarting PHP.
I also changed the PHP version from 8.2 to 8.1, and I checked from another browser, and all tests had the same problem.

**Comment by mckillo** [comment]
xprspro, review https://github.com/jmcameron/attachments/issues/63 if you J5 was migrated from J4. I think that could help you.

**Comment by parapente** [comment]
@xprspro I see many posts on various sites that correlate the error mention you wrote with page caching. Can you test with page caching disabled? Please disable the Plug-in: System - Page Cache, then clear cache and retry to upload the file that fails to upload. The extension doesn't mess with the security token so it shouldn't cause any such problem.

**Comment by xprspro** [comment]
Ok, even the "Maximum attachment size" parameter is unlimited,
I conducted new tests and found that I can upload files with zip extensions up to 40MB in size; any files exceeding 40MB result in an error.

**Comment by mckillo** [comment]
In your php.ini check the upload_max_filesize and post_max_size. I thinkn that you'll need to adjust them.

**Comment by xprspro** [comment]
After adjusting both "post_max_size" and "upload_max_filesize" to the requested values, I can now upload without errors.
Thanks a lot.
