### ISSUE TITLE
Attachments not showing in article view!

### ISSUE THREAD

**Issue by xprspro** [jmcameron/attachments#74]
Joomla 5.1.0 + Yootheme
The attachment is public permissions, but I could not see it in the article view!

**Comment by parapente** [comment]
@xprspro is the attachment published? Check Components -> Attachments -> Options and specifically in Basic tab "Attachments published by default?", "Where should attachments be placed?" and also the visibility tab to see if you have selected to have the attachments hidden.

**Comment by parapente** [comment]
If you still have problems with attachments not showing up in articles feel free to reopen.
