### ISSUE TITLE
Issues For Attachments v4.0.3

### ISSUE THREAD

**Issue by Memotas** [jmcameron/attachments#79]
Hello,

Two issues for the Attachments v4.0.3 component. Please see the images.

![image-1](https://github.com/user-attachments/assets/07446ba4-ed37-4578-ace7-5f7f86478379)
![image-2](https://github.com/user-attachments/assets/01931b34-a3b7-4a6c-8e08-505a0532ccc1)

**Comment by parapente** [comment]
Hi @Memotas. Thank you for the bug report. The first issue is already fixed in master and the second one should be fixed in PR #80 .

**Comment by Memotas** [comment]
Hello,

The translation of the Turkish language package for Attachments v4.0.3 component has been completed. If you want, I can send you the language pack. If you desired, you can use the language files.  

NOTE:

I compared all the language files with the en-GB language files for Attachments v4.0.3. I have organized all Turkish language files according to the en-GB language files and I translated all the untranslated strings. Also, I edited many previously translated strings.

**Comment by JLTRY** [comment]
@Memotas do you have the files somewhere ? Did you have a look at already existing language pack 
https://github.com/jmcameron/attachments_translations/releases/tag/Turkish-3.2.0
The package is not compatible with joomla 4.x and above, but I could adapt it to be able to install

**Comment by Memotas** [comment]
Hello,

Turkish language files for Attachments v4.0.4 component are attached. I have organized all Turkish language files according to the en-GB language files and I translated all the untranslated strings. Also, I edited many previously translated strings. Please review. 

If you desired, you can use the language files.


Turkish Translator&Math Teacher - Mehmet Taş
[tr-TR-For-attachments-4.0.4.zip](https://github.com/user-attachments/files/17698636/tr-TR-For-attachments-4.0.4.zip)
